### ISSUE TITLE
May I ask when the dataset will be released?

### ISSUE THREAD

**Issue by PteroMaplePT** [Shen-Chenhui/MReD#1]
I am very interested in Meta-Review Dataset.
I look forward to the release of the dataset.
Is there an exact release time?

**Comment by Shen-Chenhui** [comment]
Thank you for your interest! 
We are still in progress of further organising the dataset. 
Will let you know as soon as it is ready.

**Comment by GabrielLin** [comment]
Are the dataset and code ready now? @Shen-Chenhui

**Comment by Shen-Chenhui** [comment]
Hi Gabriel,

Currently due to some process requirements I am yet unable to put the dataset out to public,
but rest assured it will be released this year soon.
I will write again to you once it is released.

Yours sincerely,
Chenhui

________________________________

**Comment by Shen-Chenhui** [comment]
I have released the code and dataset. 
I am closing this issue.
