### ISSUE TITLE
Running Environment

### ISSUE THREAD

**Issue by GabrielLin** [Shen-Chenhui/MReD#2]
Could you please provide your detailed information about the running environment? For example, Python version, PyTorch version, CUDA version, CUDNN version, and all the required packages and their detailed version. Thanks.

**Comment by Shen-Chenhui** [comment]
My code is adopted from two GitHub repos where I have minimal modification.
So basically for the classification task, you can follow the setup given in the readme of https://github.com/allanj/pytorch_neural_crf, and for abstraction summarization, you can follow the setup in https://github.com/huggingface/transformers. 

In brief, you need Python >= 3.6, PyTorch >= 1.6.0, and the transformer version of 4.6.0. 

Specifically, if you want to allow input truncation of more than 1024 tokens, you need a local editable install of the transformers, then replace the `modeling_utils.py` script with my provided script (as detailed in the readme for MReD).

**Comment by GabrielLin** [comment]
Thank you for your reply. I download transformers 4.6.0 from https://github.com/huggingface/transformers/archive/refs/tags/v4.6.0.zip . I found that `modeling_utils.py` is quite different from your version besides the parts commented `# MReD`. Could you please help to check whether it is the exact file your modification based on? Thanks.

**Comment by Shen-Chenhui** [comment]
Hi, you are right. The modeling_utils.py I use was for 4.6.0.dev0. 
If you don't need the extended length of source truncation, 4.6.0 is compatible. 

If you need to modify the modeling_util.py file for extended length, I have looked through 4.6.0 version file and believe you can paste onto the original file after line 1250, using the content from my provided modeling_utils.py line 1191-1215.  (see below screenshot)
![Screenshot 2022-04-03 at 5 53 03 PM](https://user-images.githubusercontent.com/24800477/161421931-91a390d8-edc6-4d07-8b7a-d0f753c03ed0.png)

The basic logic is that, the pretrained Bart only have positional embedding trained for the first 1024 tokens. What my code does is to use the pretrained position embedding for the first 1024 tokens, and use the randomly initialized position embeddings when the BartForConditionalGeneration instance is called.

**Comment by GabrielLin** [comment]
Thank you very much. You are helpful.

**Comment by Shen-Chenhui** [comment]
Hi, sorry due to an issue in my paper link, I am changing this repo name to "MReD."

________________________________

**Comment by GabrielLin** [comment]
Got it with thanks. I have stared it before the name change. Sorry for the late reply, I miss the notification.

**Comment by Shen-Chenhui** [comment]
fixed issue and changed repo name back to "MReD"
